{% set name = "geeadd" %}
{% set version = "0.5.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8ff3c9b6de3b45a2fd056b7344cfa2e828123fe2ed90e82dc687e564d2751e4f

build:
  number: 0
  entry_points:
    - geeadd=geeadd.geeadd:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >3.5

  run:
    - beautifulsoup4 >=4.9.0
    - earthengine-api >=0.1.217
    - logzero >=1.5.0
    - requests >=2.22.0
    - python >3.5

test:
  imports:
    - geeadd
  commands:
    - geeadd --help

about:
  home: https://github.com/samapriya/gee_asset_manager_addon
  license: Apache Software
  license_family: APACHE
  license_file: LICENSE
  summary: Google Earth Engine Batch Assets Manager with Addons
  doc_url: https://samapriya.github.io/gee_asset_manager_addon/
  dev_url: https://github.com/samapriya/gee_asset_manager_addon

extra:
  recipe-maintainers:
    - samapriya
